version: '2'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: sageone/zuora
    container_name: zuora
    volumes:
      - .:/usr/src/app
    env_file:
      - configs/default.env
