name: CI

on: [push]

env:
  CI_BRANCH: "${{ github.ref_name }}"
  BUNDLE_SAGEONEGEMS__JFROG__IO: "${{ secrets.BUNDLE_SAGEONEGEMS__JFROG__IO }}"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.1', '3.0', '2.7']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Export ENV
        run: cat configs/default.env >> $GITHUB_ENV

      - name: Tests
        run: 'bundle exec rspec spec --force-color --format doc'

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/build-')
    runs-on: ubuntu-latest

    env:
      GEMS_PATH: "pkg/*.gem"
      RUBYGEMS_HOST: "https://sageonegems.jfrog.io/artifactory/api/gems/gems-local"
      JFROG_USER: "${{ secrets.JFROG_USER }}"
      JFROG_PASS: "${{ secrets.JFROG_PASS }}"

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Clear any existing packages
        run: rm -f $GEMS_PATH

      - name: Retrieve credentials
        run: |
          mkdir -p $HOME/.gem
          curl -u $JFROG_USER:$JFROG_PASS $RUBYGEMS_HOST/api/v1/api_key.yaml > $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials

      - name: Build gem
        run: bundle exec rake build zuora.gemspec

      - name: Publish
        run: gem push $GEMS_PATH
