name: RSpec
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2']
        image: localstack/localstack:latest
        env:
          SQS_ENDPOINT_STRATEGY: off
          LOCALSTACK_HOST: localhost
        ports:
          - "8085:8080"
          - "4566:4566"
        options: >-
          --health-cmd "curl http://localhost:4566/_localstack/health?reload"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Bundle
        run: bundle install
      - name: Run tests
        run: "bundle exec rspec"